.TH COLORTEST "1" "2022" "INFO MONO" "User Commands"
.SH NAME
Colortest \- Customizable Colortest
.SH SYNOPSIS
.B colortest <options>
.SH DESCRIPTION
Colortest is a tool to quickly show all your terminal colors.
.SH OPTIONS
\fB\-h, \-\-help\fR
Print help message.
.TP
\fB\-s, \-\-string\fR <string>
Set print string.
.TP
\fB\-S, \-\-separator\fR <separator>
Set separator string.
.TP
\fB\-f, \-\-fg\-modes\fR <fg-modes>
Set foreground modes list (separated by space).
.IP
Available modes: normal, bright, bold, both.
.TP
\fB\-b, \-\-bg\-modes\fR <bg-modes>
Set background modes list (separated by space).
.IP
Available modes: normal, bright.
.TP
\fB\-F, \-\-fg\-colors\fR <fg-colors>
Set foreground colors list (separated by space).
.IP
Available colors: none, label, 0 (black), 1 (red), 2 (green), 3 (yellow), 4 (blue), 5 (magenta), 6 (cyan), 7 (white).
.TP
.TP
\fB\-B, \-\-bg\-colors\fR <bg-colors>
Set background colors list (separated by space).
.IP
Available colors: none, label, 0 (black), 1 (red), 2 (green), 3 (yellow), 4 (blue), 5 (magenta), 6 (cyan), 7 (white).
.TP
.SH REPORTING BUGS
Report bugs to https://github.com/info-mono/colorstrip/issues
